version: '3'
services:
  postgres:
    image: 'postgres:latest'  
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'  
  nginx:
    depends_on:
      - api
      - client  
    restart: always
    build:  
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports: 
      - '3050:80'
  api:
    depends_on:
      - postgres
      - redis   
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules  
      - ./server:/home/node/app     
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432   
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGUSER=postgres
  worker:
    depends_on:
      - redis
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules  
      - ./worker:/home/node/app    
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379       
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules  
      - ./client:/home/node/app    
    environment:  
      - WDS_SOCKET_PORT=0      
                 


