version: '3'
services:
  nginx:
    image: 'piotrfranekjan/multi-nginx'
    mem_limit: 128m
    hostname: nginx
    ports: 
      - '80:80'
  server:
    image: 'piotrfranekjan/multi-server'
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGHOST=$PGHOST
      - PGPORT=$PGPORT  
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGUSER=$PGUSER
  worker:
    image: 'piotrfranekjan/multi-worker'
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT    
  client:
    image: 'piotrfranekjan/multi-client'
    mem_limit: 128m
    hostname: client
        