name: Deploy MultiDocker
on:
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t piotrfranekjan/multi-client-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true piotrfranekjan/multi-client-test npm run test

      - run: docker build -t piotrfranekjan/multi-client ./client 
      - run: docker build -t piotrfranekjan/multi-worker ./worker 
      - run: docker build -t piotrfranekjan/multi-server ./server
      - run: docker build -t piotrfranekjan/multi-nginx ./nginx 

      - run: docker push piotrfranekjan/multi-client 
      - run: docker push piotrfranekjan/multi-worker
      - run: docker push piotrfranekjan/multi-server
      - run: docker push piotrfranekjan/multi-nginx    

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-499934076957
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip      

           