name: Deploy MultiDocker
on:
  push:
    branches:
      - master
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Build Client
        run: docker build -t piotrfranekjan/multi-client-test -f ./client/Dockerfile.dev ./client
      - name: Run Tests
        run: docker run -e CI=true piotrfranekjan/multi-client-test npm run test    
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Login to Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Client Prod
        run: docker build -t piotrfranekjan/multi-client ./client 
      - name: Build Worker Prod
        run: docker build -t piotrfranekjan/multi-worker ./worker 
      - name: Build Server Prod
        run: docker build -t piotrfranekjan/multi-server ./server
      - name: Build Nginx Prod
        run: docker build -t piotrfranekjan/multi-nginx ./nginx 

      - name: Load Client to Dockerhub
        run: docker push piotrfranekjan/multi-client 
      - name: Load Worker to Dockerhub
        run: docker push piotrfranekjan/multi-worker
      - name: Load Server to Dockerhub
        run: docker push piotrfranekjan/multi-server
      - name: Load Nginx to Dockerhub
        run: docker push piotrfranekjan/multi-nginx    

      - name: Generate deployment package
        run: zip deploy.zip docker-compose.yml
      - name: Upload artifacts
        uses: actions/upload-artifact@v3  
        with:
          name: deploy-package
          path: deploy.zip        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3  
        with: 
          name: deploy-package   
      - name: Output content
        run: |
          ls             
          less deploy.zip 
      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: multi-docker
      #     environment_name: Multidocker-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-499934076957
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip      

           